# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "test-unit", "~> 3.3"

gem "tty-cursor", "~> 0.7.1"

gem "tty-progressbar", "~> 0.17.0"

gem "tty-prompt", "~> 0.21.0"

gem "colorize", "~> 0.8.1"

gem "artii", "~> 2.1"

gem "lolcat", "~> 100.0"

gem "httparty", "~> 0.21.0"

gem "htmlentities", "~> 4.3"
